[package]
name = "rusty-karaoke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui = "0.19.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
